Agency_Backoffice/Controllers/BusController.cs
using Agency_Backoffice.Models;
using Agency_Backoffice.Models.Common;
using Agency_Backoffice.Service;
using ClosedXML.Excel;
using ModelLibrary;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web.Mvc;

namespace Agency_Backoffice.Controllers
{
    public class BusController : Controller
    {
        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult BusReport(string btnvalue, BusFilter filter)
        {
            BusModel model = new BusModel();
            try
            {
                LoginSessionDetails lu = new LoginSessionDetails();
                if (AccountService.GetLoginSession(ref lu))
                {
                    if (btnvalue == "search")
                    {
                        UpdateModel(model);
                    }
                    filter.FilterLoginId = filter.FilterAgentId = lu.AgentRegisterSession.UID;
                    model = BusService.GetBusReport(filter);

                    TempData["BusReportFilter"] = filter;
                    TempData.Keep();
                }
            }
            catch (Exception ex)
            {
                ex.ToString();
            }
            return View(model);
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult BusRefundReport(string btnvalue, BusFilter filter)
        {
            BusRefund model = new BusRefund();
            try
            {
                LoginSessionDetails lu = new LoginSessionDetails();
                if (AccountService.GetLoginSession(ref lu))
                {
                    if (btnvalue == "search")
                    {
                        UpdateModel(filter);
                    }
                    filter.FilterLoginId = filter.FilterAgentId = lu.AgentRegisterSession.UID;
                    model.BusRefundList = BusService.GetBusRefundReport(filter);
                    model.TotalCount = model.BusRefundList.Count;

                    TempData["BusRefundFilter"] = filter;
                    TempData.Keep();
                }
            }
            catch (Exception ex)
            {
                ex.ToString();
            }
            return View(model);
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult BusRejectReport(string btnvalue, BusFilter filter)
        {
            BusReject model = new BusReject();
            try
            {
                LoginSessionDetails lu = new LoginSessionDetails();
                if (AccountService.GetLoginSession(ref lu))
                {
                    if (btnvalue == "search")
                    {
                        UpdateModel(filter);
                    }
                    filter.FilterLoginId = filter.FilterAgentId = lu.AgentRegisterSession.UID;
                    model.BusRejectList = BusService.GetBusRejectReport(filter);
                    model.TotalCount = model.BusRejectList.Count;

                    TempData["BusRejectFilter"] = filter;
                    TempData.Keep();
                }
            }
            catch (Exception ex)
            {
                ex.ToString();
            }
            return View(model);
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult BusHoldPnrReport(string btnvalue, BusFilter filter)
        {
            BusHoldPnr model = new BusHoldPnr();
            try
            {
                LoginSessionDetails lu = new LoginSessionDetails();
                if (AccountService.GetLoginSession(ref lu))
                {
                    if (btnvalue == "search")
                    {
                        UpdateModel(filter);
                    }
                    filter.FilterLoginId = filter.FilterAgentId = lu.AgentRegisterSession.UID;
                    model.BusHoldPnrList = BusService.GetBusHoldPnrReport(filter);
                    model.TotalCount = model.BusHoldPnrList.Count;
                    model.ExecutiveList = Commoncls.CommonPopulateSelectListItem(BusService.ExecutiveList());

                    TempData["BusHoldPnrFilter"] = filter;
                    TempData.Keep();
                }
            }
            catch (Exception ex)
            {
                ex.ToString();
            }
            return View(model);
        }
        public JsonResult GetBusSelectedSeatDetails(string orderid, string tinno)
        {
            List<string> result = new List<string>();
            LoginSessionDetails lu = new LoginSessionDetails();
            if (AccountService.GetLoginSession(ref lu))
            {
                result = BusService.GetBusSelectedSeatDetails(orderid, lu.AgentRegisterSession.AgencyId, tinno);
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        #region [Export To Excel]   
        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public FileResult BusReportExportToExcel()
        {
            BusFilter filter = TempData["BusReportFilter"] as BusFilter;
            TempData.Keep("BusReportFilter");
            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(BusService.ExportBusTicketReport(filter));
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Report_" + DateTime.Now.ToString("dd-MM-yyyy") + ".xlsx");
                }
            }
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public FileResult BusRefundReportExportToExcel()
        {
            BusFilter filter = TempData["BusRefundFilter"] as BusFilter;
            TempData.Keep("BusRefundFilter");
            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(BusService.BusRefundReportExportToExcel(filter));
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Report_" + DateTime.Now.ToString("dd-MM-yyyy") + ".xlsx");
                }
            }
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public FileResult BusRejectReportExportToExcel()
        {
            BusFilter filter = TempData["BusRejectFilter"] as BusFilter;
            TempData.Keep("BusRejectFilter");
            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(BusService.BusRejectReportExportToExcel(filter));
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Report_" + DateTime.Now.ToString("dd-MM-yyyy") + ".xlsx");
                }
            }
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public FileResult BusHoldPnrReportExportToExcel()
        {
            BusFilter filter = TempData["BusHoldPnrFilter"] as BusFilter;
            TempData.Keep("BusHoldPnrFilter");
            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(BusService.BusHoldPnrReportExportToExcel(filter));
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Report_" + DateTime.Now.ToString("dd-MM-yyyy") + ".xlsx");
                }
            }
        }
        #endregion
    }
}

Agency_Backoffice/Views/Bus/BusHoldPnrReport.cshtml
@model ModelLibrary.BusHoldPnr

@{
    ViewBag.Title = "BusRefundReport";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}

@{
    ViewBag.Title = "BusReport";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}
@section header{
    <link href="~/Content/fancybox/jquery.fancybox.css" rel="stylesheet" />
    <link href="~/Content/css/DatePickerMYcss.css" rel="stylesheet" />
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <style>
        .setspinner {
            position: absolute;
            right: 16px;
            top: 10px;
            z-index: 999;
            font-size: 20px;
            color: #169F85;
        }

    </style>
}
@{
    Agency_Backoffice.Models.LoginSessionDetails lu = new Agency_Backoffice.Models.LoginSessionDetails();
    if (Agency_Backoffice.Service.AccountService.GetLoginSession(ref lu))
    {
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_content">
                    <section class="wrapper">
                        <div class="row">
                            <div class="col-sm-12">
                                <section class="panel">
                                    <header class="panel-heading">
                                        <i class="icofont-airplane-alt"></i> Bus Hold Pnr Report
                                    </header>
                                    <div class="panel-body" style="padding:15px;">
                                        @using (Html.BeginForm())
                                        {
                                            <div class="row form-group">
                                                <div class="col-sm-12">
                                                    <div class="col-sm-2">
                                                        @Html.TextBoxFor(p => p.Filter.FilterFromDate, new { @class = "form-control CommanDate", placeholder = "dd/mm/yyy", autocomplete = "off" })
                                                    </div>
                                                    <div class="col-sm-2">
                                                        @Html.TextBoxFor(p => p.Filter.FilterToDate, new { @class = "form-control CommanDate", placeholder = "dd/mm/yyy", autocomplete = "off" })
                                                    </div>
                                                    <div class="col-sm-2">
                                                        @Html.TextBoxFor(p => p.Filter.FilterPnr, new { @class = "form-control", placeholder = "PNR" })
                                                    </div>
                                                    <div class="col-sm-2">
                                                        @Html.TextBoxFor(p => p.Filter.FilterOrderId, new { @class = "form-control", placeholder = "Orderid" })
                                                    </div>
                                                    <div class="col-sm-2">
                                                        @Html.TextBoxFor(p => p.Filter.FilterSource, new { @class = "form-control", placeholder = "Source" })
                                                    </div>
                                                    <div class="col-sm-2">
                                                        @Html.TextBoxFor(p => p.Filter.FilterDestination, new { @class = "form-control", placeholder = "Destination" })
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row form-group">
                                                <div class="col-sm-12">
                                                    <div class="col-sm-2">
                                                        @Html.TextBoxFor(p => p.Filter.FilterTicketNo, new { @class = "form-control", placeholder = "Ticket Number" })
                                                    </div>
                                                    <div class="col-sm-2">
                                                        @Html.TextBoxFor(p => p.Filter.FilterBusOperator, new { @class = "form-control", placeholder = "Bus Operator" })
                                                    </div>
                                                    <div class="col-sm-2">
                                                        @Html.DropDownListFor(m => m.Filter.FilterExecid, Model.ExecutiveList, "Select Executive", new { @class = "form-control " })
                                                    </div>
                                                    @if (lu.AgentRegisterSession.User_Type == "DI")
                                                    {
                                                        <div class="col-sm-2">
                                                            @Html.TextBoxFor(p => p.Filter.AgencyName, new { @class = "form-control", placeholder = "AgencyName.." })
                                                            <i class="fa fa-spin fa-spinner hidden setspinner setlevfromspinner"></i>
                                                            @Html.HiddenFor(p => p.Filter.AgentId)
                                                        </div>
                                                    }
                                                    <div class="col-sm-2">
                                                        <button type="submit" name="btnvalue" id="btnSubmit" class="btn btn-success form-control" value="search" onclick="return CheckForm()">Search</button>
                                                    </div>
                                                    <div class="col-sm-2">
                                                        <button type="submit" name="btnvalue" id="btnReset" class="btn btn-danger form-control" value="reset" onclick="return ResetFilter()">Reset</button>
                                                    </div>
                                                </div>
                                            </div>
                                        }
                                    </div>
                                </section>
                            </div>
                        </div>
                    </section>


                    <section class="wrapper">
                        <div class="row">
                            <div class="col-sm-12">
                                <section class="panel">
                                    <header class="panel-heading">
                                        <i class="icofont-search-document"></i>Report
                                        <span class="tools pull-right">
                                            @if (Model.TotalCount > 0)
                                            {
                                                using (Html.BeginForm("BusReportExportToExcel", "Bus", FormMethod.Post))
                                                {
                                                    <button type="submit" style="cursor:pointer;"><span class="icofont-file-excel"></span> Export</button>
                                                }
                                            }
                                        </span>
                                    </header>
                                    <div class="panel-body table-responsive" style="overflow: scroll; max-height: 600px;">
                                        <table class="table table-collapse-phone" cellspacing="0" width="100%" ShowHeaderWhenEmpty="true">
                                            <thead>
                                                <tr>

                                                    <th class="sticky-header">Ticket No</th>
                                                    <th>Journey Date</th>
                                                    <th>Order Id</th>
                                                    <th>Agent Id</th>
                                                    <th>Trip Id</th>
                                                    <th>Destination</th>
                                                    <th>Bus Operator</th>
                                                    <th>Seat No</th>
                                                    <th>Net Fare</th>
                                                    <th>Pnr</th>
                                                    <th>Booking Status</th>
                                                    <th>Created Date</th>
                                                    <th>Payment Mode</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @if (Model.TotalCount > 0)
                                                {
                                                    foreach (var item in Model.BusHoldPnrList)
                                                    {
                                                        <tr>
                                                            <td class="sticky-row"><a href="#" target="_blank">@item.TICKETNO</a></td>
                                                            <td>@item.JOURNEYDATE</td>
                                                            <td>@item.ORDERID</td>
                                                            <td>@item.AGENTID</td>
                                                            <td>@item.TRIPID</td>
                                                            <td>@item.DESTINATION</td>
                                                            <td>@item.BUSOPERATOR</td>
                                                            <td>@item.SEATNO</td>
                                                            <td>@item.TA_NET_FARE</td>
                                                            <td>@item.PNR</td>
                                                            <td>@item.BOOKINGSTATUS</td>
                                                            <td>@item.CREATEDDATE</td>
                                                            <td>@item.PaymentMode</td>
                                                        </tr>
                                                    }
                                                }
                                                else
                                                {
                                                    <tr class="text-center">
                                                        <td colspan="13"><span class="text-danger">Record not found !</span></td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </section>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
        }
    }
        @section footer{
            <script src="~/Content/fancybox/jquery.fancybox.js"></script>
            <script src="~/Content/fancybox/fancyboxpopupopen.js"></script>
            <script src="~/Content/js/loginpage/DatePicker.js"></script>
            <script>
                CheckForm = () => { $("#btnSubmit").html("Searching...<i class='fa fa-spinner fa-pulse'></i>"); }
                ResetFilter = () => { $("#btnReset").html("Resetting...<i class='fa fa-spinner fa-pulse'></i>"); }
            </script>
        }