Agency_Backoffice/Controllers/FlightReportController.cs
using Agency_Backoffice.Models;
using Agency_Backoffice.Models.Common;
using Agency_Backoffice.Service;
using ClosedXML.Excel;
using DataBaseLibrary.Flight;
using DataBaseLibrary.MailingCredentiaL;
using ModelLibrary;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using UtilityLibrary;

namespace Agency_Backoffice.Controllers
{
    public class FlightReportController : Controller
    {
        public ActionResult TicketReport(FlightTicketFilter filter)
        {
            FlightTicketReport model = new FlightTicketReport();
            try
            {
                LoginSessionDetails lu = new LoginSessionDetails();
                if (AccountService.GetLoginSession(ref lu))
                {
                    filter.UserType = lu.AgentRegisterSession.User_Type;
                    filter.Loginid = lu.AgentRegisterSession.UID;
                    filter.Status = FlightStatus.Ticketed.ToString();
                }

                model.FlightTicketReportList = FlightReportService.GetFlightTicketReports(filter);
                model.Totalcount = model.FlightTicketReportList.Count;

                TempData["FlightFilter"] = filter;
                TempData.Keep();
            }
            catch (Exception ex)
            {
                ex.ToString();
            }

            return View(model);
        }
        public ActionResult TicketDetailsReport(string orderId, string transId)
        {
            SingleTicketReportModel model = new SingleTicketReportModel();
            try
            {
                model.BookingDetail = FlightReportService.GetBookingDetails(orderId);
                model.PaymentDetail = FlightReportService.GetPayementProcess(orderId);
            }
            catch (Exception ex)
            {
                ex.ToString();
            }

            return View(model);
        }
        public JsonResult GetTicketDetails(string orderid)
        {
            return Json(FlightReportService.GetTicketDetails(orderid), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Invoice(string orderId)
        {
            FlightInvoice model = new FlightInvoice();
            try
            {
                //    model.FlightInvoiceList = FlightReportService.GetInvoiceDetails(orderId);
                //    model.PaxList = FlightReportService.SelectPaxDetail(orderId, "");
                //    model.FltDetailsList = FlightReportService.SelectFlightDetail(orderId);
                //    model.FlightInvoiceList[0].DepartureDate = Commoncls.GetSpilitedDateFormate(model.FlightInvoiceList[0].DepartureDate);
                //    model.AgencyList = FlightReportService.GetAgencyDetailByAgentId(model.FlightInvoiceList[0].AgentId);
                model.OrderId = orderId;
                model.Invoicecopy = FlightDataBase.InvoiceCopy(orderId);

            }
            catch (Exception ex)
            {
                ex.ToString();
            }
            return View(model);
        }
        public ActionResult ReIssueReFund(ReIssueReFund model, string paxid, string paxname, string orderid, string gdspnr, string paxtype, string actiontype)
        {
            try
            {
                if (!string.IsNullOrEmpty(paxid) && !string.IsNullOrEmpty(actiontype))
                {
                    if (actiontype == "reissue")
                    {
                        string firstStatus = FlightReportService.CheckTktNo(Convert.ToInt32(paxid), orderid, gdspnr);

                        model = FlightReportService.GetTicketdIntl(Convert.ToInt32(paxid), paxtype);

                        string newpaxid = paxid;

                        if (!string.IsNullOrEmpty(model.ResuID))
                        {
                            ReIssueReFund Paxds = FlightReportService.OldPaxInfo(model.ResuID, model.Title, model.FName, model.MName, model.LName, model.PaxType);
                            //newpaxid = Paxds.PaxId.ToString();
                        }

                        string secondStatus = FlightReportService.CheckTktNo(Convert.ToInt32(newpaxid.Trim()), model.OrderId, model.PNR);

                        if (secondStatus == "0")
                        {
                        }
                        else if (secondStatus == "Reissue request can not be accepted for past departure date." && actiontype == "refund")
                        {
                        }
                        else if ((secondStatus == "0" || secondStatus == "Reissue request can not be accepted for past departure date." || secondStatus == "Given ticket number is already ReIssued") || firstStatus == "Refund/Reissue request can not be accepted upto 4 hour prior to departure date. Please contact to airline directly." && actiontype == "refund")
                        {

                        }
                        else if (firstStatus == "Refund/Reissue request can not be accepted upto 4 hour prior to departure date. Please contact to airline directly." && actiontype == "refund")
                        {
                        }
                        else
                        {
                            TempData["Message"] = secondStatus;
                        }
                    }
                    else
                    {
                        string firstStatus = FlightReportService.CheckTktNo(Convert.ToInt32(paxid), orderid, gdspnr);

                        model = FlightReportService.GetTicketdIntl(Convert.ToInt32(paxid), paxtype);

                        string newpaxid = paxid;

                        if (!string.IsNullOrEmpty(model.ResuID))
                        {
                            ReIssueReFund Paxds = FlightReportService.OldPaxInfo(model.ResuID, model.Title, model.FName, model.MName, model.LName, model.PaxType);
                            //newpaxid = Paxds.PaxId.ToString();
                        }

                        string secondStatus = FlightReportService.CheckTktNo(Convert.ToInt32(newpaxid.Trim()), model.OrderId, model.PNR);

                        if (secondStatus == "0")
                        {
                        }
                        else if (secondStatus == "Reissue request can not be accepted for past departure date." && actiontype == "refund")
                        {
                        }
                        else if ((secondStatus == "0" || secondStatus == "Reissue request can not be accepted for past departure date." || secondStatus == "Given ticket number is already ReIssued") || firstStatus == "Refund/Reissue request can not be accepted upto 4 hour prior to departure date. Please contact to airline directly." && actiontype == "refund")
                        {

                        }
                        else if (firstStatus == "Refund/Reissue request can not be accepted upto 4 hour prior to departure date. Please contact to airline directly." && actiontype == "refund")
                        {
                        }
                        else
                        {
                            TempData["Message"] = secondStatus;
                        }
                    }

                    model.ActionType = actiontype.ToUpper();
                }

                model.PaxName = paxname;
            }
            catch (Exception ex)
            {
                ex.ToString();
                //clsErrorLog.LogInfo(ex)
            }

            return View(model);
        }
        [HttpPost]
        public ActionResult ReIssueReFund(ReIssueReFund model, string actiontype)
        {
            try
            {
                if (model.ActionType.ToLower() == "refund")
                {
                    try
                    {
                        string TickeNo = "";
                        string Status = "0";
                        Status = FlightReportService.CheckTktNo(Convert.ToInt32(model.PaxID), model.OrderId, model.PNR);
                        if (Status != "0")
                        {
                            TickeNo = model.PaxID;
                        }
                        DataSet Paxds = FlightDataBase.GetPaxDetails(model.OrderId);
                        DataRow[] PaxDtRow = Paxds.Tables[0].Select("PaxId=" + model.PaxID + "");
                        // Select requested record for Reissue and Refund                       
                        ReIssueReFund fltdss = FlightReportService.GetTicketdIntl(Convert.ToInt32(model.PaxID), PaxDtRow[0]["PaxType"].ToString());
                        if (fltdss != null && !string.IsNullOrEmpty(fltdss.UserID))
                        {
                            string status = FlightReportService.CheckTktNo(Convert.ToInt32(model.PaxID), model.OrderId, model.PNR);

                            if (status == "0")
                            {
                                fltdss.Remark = model.Remark;
                                fltdss.PaxID = model.PaxID;
                                fltdss.ProjectID = !string.IsNullOrEmpty(model.ProjectID) ? model.ProjectID : "Nothing";
                                fltdss.BillNoAir = !string.IsNullOrEmpty(model.BillNoAir) ? model.BillNoAir : "Nothing";
                                fltdss.BillNoCorp = "Nothing";
                                fltdss.ReqTyp = "C";
                                fltdss.Status = FlightStatus.Pending.ToString();
                                fltdss.RefundID = UtilityModel.GenrateRandomTransactionId("RFND", 10, "1234567890");

                                if (model.ActionType.ToLower() == "refund")
                                {
                                    bool isInsert = FlightReportService.InsertReIssueCancelIntl(fltdss);

                                    LoginSessionDetails lu = new LoginSessionDetails();
                                    if (AccountService.GetLoginSession(ref lu))

Agency_Backoffice/Controllers/RailController.cs
using Agency_Backoffice.Models;
using Agency_Backoffice.Service;
using ClosedXML.Excel;
using ModelLibrary;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Agency_Backoffice.Controllers
{
    public class RailController : Controller
    {
        public ActionResult RailReport(RailModelFilter filter)
        {
            RailModel model = new RailModel();
            try
            {
                LoginSessionDetails lu = new LoginSessionDetails();
                if (AccountService.GetLoginSession(ref lu))
                {                    
                    filter.Loginid = lu.AgentRegisterSession.UID;                   
                }
                model.RailReportList = FlightReportService.GetRailReports(filter);
                model.Totalcount = model.RailReportList.Count;
                TempData["RailFilter"] = filter;
                TempData.Keep();
            }
            catch (Exception ex)
            {
                ex.ToString();
            }

            return View(model);
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public FileResult RailExportToExcel()
        {
            RailModelFilter filter = TempData["RailFilter"] as RailModelFilter;
            TempData.Keep("RailFilter");
            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(FlightReportService.ExportRailTicketReport(filter));
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Report_" + DateTime.Now.ToString("dd-MM-yyyy") + ".xlsx");
                }
            }
        }
    }
}

Agency_Backoffice/Views/Rail/RailReport.cshtml
@model ModelLibrary.RailModel
@using ModelLibrary;

@{
    ViewBag.Title = "TicketReport";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}
@section header{
    <link href="~/Content/css/DatePickerMYcss.css" rel="stylesheet" />
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <style>
        @@media(min-width: 992px) {
            .modal-lg {
                max-width: 85%;
                margin-left: 15%;
            }
        }

        .setspinner {
            position: absolute;
            right: 16px;
            top: 10px;
            z-index: 999;
            font-size: 20px;
            color: #169F85;
        }
        .table thead th {
            background: #dddddd;
        }
            .table {
            width: max-content !important;
        }
        .sticky-header:first-child {          
            z-index: 4 !important;
        }
    </style>

}

@{
    Agency_Backoffice.Models.LoginSessionDetails lu = new Agency_Backoffice.Models.LoginSessionDetails();
    if (Agency_Backoffice.Service.AccountService.GetLoginSession(ref lu))
    {

        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_content">
                    <section class="wrapper">
                        <div class="row">
                            <div class="col-sm-12">
                                <section class="panel">
                                    <header class="panel-heading">
                                        <i class="icofont-airplane-alt"></i>  Rail Report
                                    </header>
                                    <div class="panel-body" style="padding:15px;">
                                        @using (Html.BeginForm("RailReport", "Rail", FormMethod.Post))
                                        {
                                            <div class="row form-group">
                                                <div class="col-sm-12">
                                                    <div class="col-sm-4">
                                                        @Html.TextBoxFor(p => p.FromDate, new { @class = "form-control CommanDate", placeholder = "dd/mm/yyy", autocomplete = "off" })
                                                    </div>
                                                    <div class="col-sm-4">

                                                        @Html.TextBoxFor(p => p.ToDate, new { @class = "form-control CommanDate", placeholder = "dd/mm/yyy", autocomplete = "off" })
                                                    </div>
                                                    <div class="col-sm-4">
                                                        <input type="submit" class="btn btn-success form-control maincss" style="cursor:pointer;" onclick="return CheckForm()" value="SEARCH RESULT" />
                                                        <span class="btn btn-success form-control tempscss hidden">PLEASE WAIT..<i class="fa fa-spinner fa-spin"></i></span>
                                                    </div>
                                                </div>
                                            </div>
                                        }
                                    </div>
                                </section>
                            </div>
                        </div>
                    </section>
                    <section class="wrapper">
                        <div class="row">
                            <div class="col-sm-12">
                                <section class="panel">
                                    <header class="panel-heading">
                                        <i class="icofont-search-document"></i>Rail Report
                                        <span class="tools pull-right">
                                            @if (Model.Totalcount > 0)
                                            {
                                                using (Html.BeginForm("RailExportToExcel", "FlightReport", FormMethod.Post))
                                                {
                                                    <button type="submit" style="cursor:pointer;"><span class="icofont-file-excel"></span> Export</button>
                                                }
                                            }
                                        </span>
                                    </header>
                                    <div class="panel-body">
                                        <div class="table-responsive" style="height: 450px;">
                                            <table class="table table-collapse-phone" cellspacing="0" ShowHeaderWhenEmpty="true" id="tblRecord">
                                                <thead>
                                                    <tr>
                                                        <th class="sticky-header">Agency Name</th>
                                                        <th>AgencyID</th>
                                                        <th>Track Id</th>
                                                        <th>Reservation Id</th>
                                                        <th>PNR NO</th>
                                                        <th>Class</th>
                                                        <th>Reference No</th>
                                                        <th>Debit Amount</th>
                                                        <th>Status</th>
                                                        <th>Booking Date</th>
                                                    </tr>
                                                </thead>
                                                <tbody data-show="true" data-id="ddes">
                                                    @if (Model.Totalcount > 0)
                                                    {
                                                        foreach (var item in Model.RailReportList)
                                                        {
                                                            <tr>

                                                                <td class="sticky-row">@item.AgencyName</td>
                                                                <td>@item.AgencyId</td>
                                                                <td>@item.LedgerTrackId</td>
                                                                <td>@item.ReservationId</td>
                                                                <td>
                                                                    @item.PNR_NO
                                                                </td>
                                                                <td>
                                                                    @item.Class
                                                                </td>
                                                                <td>@item.ReferenceNo</td>
                                                                <td>@item.LedDebit</td>
                                                                <td>
                                                                    @if (item.BookingStatus == "success")
                                                                    {
                                                                        <span style='color:green;font-weight:bold;'>SUCCESS</span>
                                                                    }
                                                                    else if (item.BookingStatus == "failed")
                                                                    {
                                                                        <span style='color:red;font-weight:bold;'>FAILED</span>
                                                                    }
                                                                    else
                                                                    {
                                                                        <span style='color:orange;font-weight:bold;'>NOT CONFIRMED</span>
                                                                    }
                                                                </td>

                                                                <td>@item.BookingDate</td>
                                                            </tr>
                                                        }
                                                    }
                                                    else
                                                    {
                                                        <tr>
                                                            <td colspan="9" class="text-center">
                                                                <p class="text-danger">No result found!</p>
                                                            </td>
                                                        </tr>
                                                    }
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <br />
                                    <br />
                                </section>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    }
}
@section footer{
    <script src="~/Content/js/loginpage/DatePicker.js"></script>
}